name: docker-${USER_NAME}
services:
  php:
    build: 
      context: .
      args:
        HTTP_PORT: ${HTTP_PORT}
        DEBUG_PORT: ${DEBUG_PORT}
        USER_NAME: ${USER_NAME}
    ports:
      - "0.0.0.0:${HTTP_PORT}:${HTTP_PORT}"
      - "0.0.0.0:${DEBUG_PORT}:${DEBUG_PORT}"
    volumes:
      - ./dev:/app
    container_name: docker-${USER_NAME}
    network_mode: host

