name: docker-${USER_NAME}-project
services:
  php:
    build: 
      context: .
      args:
        HTTP_PORT: ${HTTP_PORT}
        DEBUG_PORT: ${DEBUG_PORT}
        USER_NAME: ${USER_NAME}
    ports:
      - "0.0.0.0:${HTTP_PORT}:${HTTP_PORT}"
      - "0.0.0.0:${DEBUG_PORT}:${DEBUG_PORT}"
    volumes:
      - ./dev:/app
      - ./logs:/app/logs
    image: docker-${USER_NAME}
    container_name: docker-${USER_NAME}
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: '4'
