version: "3.8"

services:
  php:
    build: .
    ports:
      - "8920:80"
      - "9920:9003"
    volumes:
      - "../quartup:/app"
      - "./90-quartup.ini:/usr/local/etc/php/conf.d/90-quartup.ini"
      - "/home/jmmunoz/Desarrollo:/var/log/apache2"
    container_name: "quartup-jmmunoz"
    env_file:
      - .env
    network_mode: host
