version: '3.8'

services:
  php:
    build: 
      context: .
      args:
        HTTP_PORT: ${HTTP_PORT}
        DEBUG_PORT: ${DEBUG_PORT}
        USER_NAME: ${USER_NAME}
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
    volumes:
      - ./dev:/app
    container_name: docker-${USER_NAME}
    network_mode: host
    expose:
      - "${DEBUG_PORT}"
